services:
  api-v1:
    build:
      context: ./api
    container_name: go-api
    expose:
      - "8080"
    restart: unless-stopped

  www:
    build:
      dockerfile: ./Dockerfile.haproxy
      context: .
    container_name: haproxy
    ports:
      - "8080:80"
    depends_on:
      - api-v1
    restart: unless-stopped

